class QuestionsText {
  static final questionPartsA = <String>[
    "WHAT ASPECTS ",
    "WHAT STRATEGIES ",
    "HOW DO YOU KEEP ",
    "WHAT CHALLENGES ",
    "WHAT TYPE ",
    "HOW DO YOU s"
  ];

  static final questionPartsB = <String>[
    "OF BOXING PROMOTION DO YOU FOCUS ON THE MOST?",
    "DO YOU FIND MOST EFFECTIVE FOR PROMOTING BOXING MATCHES?",
    "FANS ENGAGED BETWEEN MAJOR BOXING EVENTS?",
    "DO YOU ENCOUNTER IN MARKETING BOXING EVENTS?",
    "OF CONTENT RESONATES MOST WITH BOXING FANS?",
    "MEASURE THE SUCCESS OF YOUR BOXING MARKETING CAMPAIGNS?"
  ];

  static final answersA = <String>[
    "BUILDING FIGHTER PROFILES",
    "CELEBRITY ENDORSEMENTS",
    "REGULAR UPDATES ON BOXERS' TRAINING",
    "SECURING SPONSORSHIPS",
    "FIGHTER INTERVIEWS AND STORIES",
    "INCREASE IN TICKET SALES"
  ];

  static final answersB = <String>[
    "EVENT ADVERTISING",
    "HIGH-QUALITY PROMOTIONAL VIDEOS",
    "HOSTING FAN INTERACTION SESSIONS",
    "REACHING A BROADER AUDIENCE",
    "TRAINING AND PREPARATION VIDEOS",
    "GROWTH IN SOCIAL MEDIA FOLLOWING"
  ];

  static final answersC = <String>[
    "SPONSORSHIP ACQUISITION",
    "INTERACTIVE FAN CONTESTS",
    "PROVIDING HISTORICAL MATCH HIGHLIGHTS",
    "MAINTAINING FAN INTEREST",
    "LIVE EVENT COVERAGE",
    "ENGAGEMENT RATES ON PROMOTIONAL CONTENT"
  ];

  static final answersD = <String>[
    "FAN ENGAGEMENT",
    "EXCLUSIVE BEHIND-THE-SCENES CONTENT",
    "RUNNING TRIVIA AND QUIZ CONTESTS",
    "MANAGING PROMOTIONAL BUDGETS",
    "HISTORICAL FIGHT ANALYSIS",
    "SPONSORSHIP DEALS SECURED"
  ];
}
